### ISSUE TITLE
ER_FIELD_IN_ORDER_NOT_SELECT error

### ISSUE THREAD

**Issue by philchass** [allnulled/mysql-schema#1]
MacOS
MySQL 8.0.22

node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_FIELD_IN_ORDER_NOT_SELECT: Expression #1 of ORDER BY clause is not in SELECT list, references column 'information_schema.TABLES.TABLE_SCHEMA' which is not in SELECT list; this is incompatible with DISTINCT
    at Query.Sequence._packetToError (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/usr/local/lib/node_modules/mysql-schema/node_modules/mysql/lib/Connection.js:198:25)
    at /usr/local/lib/node_modules/mysql-schema/src/index.js:188:15
    at new Promise (<anonymous>)
    at Function.getSchema (/usr/local/lib/node_modules/mysql-schema/src/index.js:147:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/mysql-schema/bin/mysql-schema:55:40)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ER_FIELD_IN_ORDER_NOT_SELECT',
  errno: 3065,
  sqlMessage: "Expression #1 of ORDER BY clause is not in SELECT list, references column 'information_schema.TABLES.TABLE_SCHEMA' which is not in SELECT list; this is incompatible with DISTINCT",
  sqlState: 'HY000',
  index: 0,
  sql: '\n' +
    '\t\t\tSELECT DISTINCT\n' +
    "\t\t\t    TABLES.TABLE_SCHEMA AS '$database',\n" +
    "\t\t\t    TABLES.TABLE_NAME AS '$table',\n" +
    "\t\t\t    # TABLES.TABLE_TYPE AS '$tableType',\n" +
    "\t\t\t    COLUMNS.COLUMN_NAME AS '$column',\n" +
    "\t\t\t    COLUMNS.COLUMN_TYPE AS '$columnType',\n" +
    "\t\t\t    COLUMNS.IS_NULLABLE AS '$isColumnNullable',\n" +
    "\t\t\t    COLUMNS.COLUMN_DEFAULT AS '$defaultColumnValue',\n" +
    "\t\t\t    COLUMNS.EXTRA AS '$extraColumnInformation',\n" +
    "\t\t\t    COLUMNS.ORDINAL_POSITION AS '$ordinalColumnPosition',\n" +
    "\t\t\t    COLUMNS.CHARACTER_MAXIMUM_LENGTH AS '$maximumCharactersLength',\n" +
    "\t\t\t    IF(LOCATE(' unsigned', COLUMNS.COLUMN_TYPE) > 0,1,0) AS '$isUnsigned',\n" +
    "\t\t\t    COLUMNS.EXTRA LIKE '%auto_increment%' AS '$isAutoIncrement',\n" +
    "\t\t\t    KEY_COLUMN_USAGE.CONSTRAINT_NAME AS '$boundConstraint',\n" +
    "\t\t\t    KEY_COLUMN_USAGE.REFERENCED_TABLE_NAME AS '$referencedTable',\n" +
    "\t\t\t    KEY_COLUMN_USAGE.REFERENCED_COLUMN_NAME AS '$referencedColumn'\n" +
    '\t\t\tFROM INFORMATION_SCHEMA.TABLES\n' +
    '\t\t\tLEFT JOIN INFORMATION_SCHEMA.COLUMNS ON\n' +
    '\t\t\t    COLUMNS.TABLE_SCHEMA = TABLES.TABLE_SCHEMA AND\n' +
    '\t\t\t    COLUMNS.TABLE_NAME = TABLES.TABLE_NAME\n' +
    '\t\t\tLEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ON\n' +
    '\t\t\t    KEY_COLUMN_USAGE.TABLE_SCHEMA = TABLES.TABLE_SCHEMA AND\n' +
    '\t\t\t    KEY_COLUMN_USAGE.TABLE_NAME = TABLES.TABLE_NAME AND\n' +
    '\t\t\t    KEY_COLUMN_USAGE.COLUMN_NAME = COLUMNS.COLUMN_NAME\n' +
    '\t\t\tWHERE\n' +
    "\t\t\t    TABLES.TABLE_SCHEMA = 'XXXXXX' AND\n" +
    "\t\t\t    TABLES.TABLE_TYPE = 'BASE TABLE'\n" +
    '\t\t\tORDER BY TABLES.TABLE_SCHEMA ASC, TABLES.TABLE_NAME ASC, COLUMNS.COLUMN_NAME ASC;'
}

**Comment by philchass** [comment]
/usr/local/lib/node_modules/mysql-schema/src/index.js

Putting in comment
ORDER BY TABLES.TABLE_SCHEMA ASC, TABLES.TABLE_NAME ASC, COLUMNS.COLUMN_NAME ASC;`;
on line 80 fixes the issue.
